### ISSUE TITLE
Error building (Reproduced from comment on AUR package)

### ISSUE THREAD

**Issue by gatlinnewhouse** [mathieujobin/netvirt-agent-git#2]
> **Keridos commented on 2017-04-27 13:22**
> 
> Fails to build for me:
> 
> In file included from /usr/include/openssl/ui.h:13:0,
> from /usr/include/openssl/engine.h:29,
> from /build/netvirt-agent-git/src/netvirt-agent-git/libnvcore/src/crypto.c:26:
> /usr/include/openssl/err.h:247:1: note: declared here
> DEPRECATEDIN_1_0_0(void ERR_remove_state(unsigned long pid))
> ^
> make[2]: *** [libnvcore/src/CMakeFiles/nvcore.dir/build.make:231: libnvcore/src/CMakeFiles/nvcore.
> dir/crypto.c.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:109: libnvcore/src/CMakeFiles/nvcore.dir/all] Error 2
> make: *** [Makefile:161: all] Error 2
> ==> ERROR: A failure occurred in package().
> Aborting...
> ==> ERROR: Build failed, check /home/nico/chroot/nico/build
> makechrootpkg -c -r $CHROOT 30.01s user 1.86s system 63% cpu 50.027 total

**Comment by mathieujobin** [comment]
this error is for legacy client which does not support openssl 1.1

please try latest client with https://my.dynvpn.com/

please let me know if you need help migrating from the old client/network to the new
I can provide professional assistance
